# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: MITRE Update

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python3 pull-all-techniques.py
    - name: Update timestamp
      run: |
        date > .lastcheck
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-updated output"
        commit_user_name: kfriede
        commit_user_email: github@kfriede.com
        commit_author: Kevin Friedemann <github@kfriede.com>
